### PR TITLE
fix: removal of the gray color in the scoring results

### LINKED ISSUE #577: STAR scoring results shouldn't include the color gray
image

### PR DESCRIPTION
**Pull request by DubemObi**
## Description
Fixes #577 

Made the change to remove the gray color from the scoring results

## Screenshots / Videos (frontend only) 

> Be sure to include both desktop and mobile views (mobile could be as low as 320 px wide) 

## Related Issues

> For example, add ``fixes #10`` to close issue #10

### CODE REVIEW

**Comment by ArendPeter** [comment]
Looks great! Thanks for making the change. 

I still need to look through it, but could you update the PR to also add yourself to the contributor list? 

That'll be in the About.tsx file, and you'll just need to add your github user name and id to the list (your id is 109088909)

**Comment by DubemObi** [comment]
Okay, done

**Review by ArendPeter — APPROVED** [review]
Looks good! Thank you for the contribution!

**Review by ArendPeter — APPROVED** [review]
Looks good! Thank you for the contribution!

**Pull request merged**
