### PR TITLE
Adding more structure to back end

### PR DESCRIPTION
**Pull request by mikefranze**
Moved routes and other functions into their own folders and files.

### CODE REVIEW

**Comment by ArendPeter** [comment]
I'm not familiar with the ``.controllers`` / ``.routes`` file name pattern. It seems redundant since they match the folder name. Is there another benefit for them?

**Review by ArendPeter — APPROVED** [review]
Looks good! It's a lot cleaner and organized now :D

**Comment by mikefranze** [comment]
> I'm not familiar with the `.controllers` / `.routes` file name pattern. It seems redundant since they match the folder name. Is there another benefit for them?

I'm not sure either, I've just run into 2 different example projects that used that convention so I used it too.

**Comment by ArendPeter** [comment]
> > I'm not familiar with the `.controllers` / `.routes` file name pattern. It seems redundant since they match the folder name. Is there another benefit for them?
> 
> I'm not sure either, I've just run into 2 different example projects that used that convention so I used it too.

Cool, that's good enough for me :)

**Pull request merged**
