### PR TITLE
Add graphs to the results page

### LINKED ISSUE #245: Research visualization tools for the results page
Recharts looks promising for basic charts: https://www.youtube.com/watch?v=-CwzaTKniH4
Chart js is another option: https://www.youtube.com/watch?v=RF57yDglDfE
And here's a comparison between the 2: https://www.youtube.com/watch?v=Gj0ZOr0N6Ck
Seems like recharts is prettier and easier to use

For more custom visualizations we can also draw directly to a canvas https://www.youtube.com/watch?v=K8HICLm-Jj0

More of a note to self, but this scrolling library also looks cool: https://www.youtube.com/watch?v=OAx0we521sk

### PR DESCRIPTION
**Pull request by ArendPeter**
Add graphs and a lot of other tweaks to the results page

https://github.com/Equal-Vote/star-server/assets/9289903/a3715e23-5f5f-4b69-bd5a-98252a907a63

<details><summary>First Recording</summary>
https://github.com/Equal-Vote/star-server/assets/9289903/4f7a67b3-de06-47e7-acc7-836fba6c65a7
</details>

fixes #245

### CODE REVIEW

**Comment by mikefranze** [comment]
Looks great! One thing to keep in mind though is the responsivity to different screen sizes. 

https://github.com/Equal-Vote/star-server/assets/41272412/9d765e0c-2aa6-45a2-bbc3-75acdcce7593

I would avoid specifying anything in px and use [breakpoints ](https://mui.com/material-ui/react-grid/#responsive-values) to adjust props based on screen size.

**Comment by ArendPeter** [comment]
Note to self, these are the elections I'm using to test responsiveness

http://localhost:3000/Election/fe4ab8ee-6a51-4c14-a1fa-fc4ceceeeed2/results
http://localhost:3000/Election/b7f8e4b0-f432-48cb-9987-46909dfaf1aa/results
http://localhost:3000/Election/ac599071-27c7-4357-b220-33c3cff29281/results

**Comment by ArendPeter** [comment]
- [ test ] test

**Comment by ArendPeter** [comment]
image
Another update with bolded fonts on the graphs

**Comment by mikefranze** [comment]
Looks great! For the long name case I'm wondering if it'd be better to just truncate names past a certain length. Probably good as is for now.

**Review by mikefranze — APPROVED** [review]

**Comment by ArendPeter** [comment]
> Looks great! For the long name case I'm wondering if it'd be better to just truncate names past a certain length. Probably good as is for now.

Sounds good, I made an issue https://github.com/Equal-Vote/star-server/issues/290

Also today I learned you can quick create issues from PR comments, I'm going to start doing that more

image

**Pull request merged**
